#!/bin/bash

echo "=== Ascento 参数调整脚本 ==="
echo ""
echo "质心位置修正：从 -40mm 改为 -24.5mm"
echo "theta_eq 修正：从 0.367 rad (21°) 改为 0.244 rad (14°)"
echo ""
echo "请打开串口终端："
echo "  ./scripts/serial.sh"
echo ""
echo "然后依次执行以下命令："
echo ""
echo "1. 查看当前状态："
echo "   robot status"
echo ""
echo "2. 修正 theta_eq："
echo "   robot param theta_eq 0.244"
echo ""
echo "3. 调整增益（可选，如果机器人振荡）："
echo "   robot param k_pitch_c -6.0"
echo "   robot param k_pitch_rate_c -1.5"
echo ""
echo "4. 增大 stiction（如果小角度不响应）："
echo "   robot param stiction_ma 3000"
echo ""
echo "5. 保存参数："
echo "   robot param save"
echo ""
echo "6. 验证参数："
echo "   robot param"
echo ""
echo "7. 测试站立："
echo "   robot enable 1"
echo ""
echo "=== 调参建议 ==="
echo ""
echo "如果机器人仍然站不起来："
echo "- 振荡（左右晃）：减小 k_pitch_c 绝对值，如 -4.0"
echo "- 无力倒下：增大 k_pitch_c 绝对值，如 -8.0"
echo "- 小角度不响应：增大 stiction_ma，如 3500"
echo "- 电流饱和（轮子啸叫）：增大 current_limit，如 2500"
echo ""
echo "如果需要恢复默认值："
echo "   robot param reset"
